POST https://rahulshettyacademy.com/oauthapi/oauth2/resourceOwner/token
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="client_id"
Content-Type: text/plain

692183103107-p0m7ent2hk7suguv4vq22hjcfhcr43pj.apps.googleusercontent.com
--boundary
Content-Disposition: form-data; name="client_secret"
Content-Type: text/plain

erZOWM9g3UtwNRj340YYaK_W
--boundary
Content-Disposition: form-data; name="grant_type"
Content-Type: text/plain

client_credentials
--boundary
Content-Disposition: form-data; name="scope"
Content-Type: text/plain

trust
--boundary--

###
GET https://rahulshettyacademy.com/oauthapi/getCourseDetails?access_token=gKvFFc3hXlGznLsqnWPEeQ==
